/**
 * What has shipped, newest first.
 *
 * Hand-written rather than generated from `git log`, and deliberately so: the
 * build has no git history to read on a deploy host, and a commit subject is
 * written for whoever maintains the code rather than for whoever uses it.
 *
 * KEEP THIS UPDATED WITH EVERY RELEASE — add an entry at the top with the
 * version, the date, and what actually changed for someone using the app.
 * `changes` is what is new or different, `fixes` is what was broken and is not
 * any more. Either may be omitted.
 *
 * `version` is the SemVer this release carries, and it must match the three
 * package.json files. A commit that changes nothing a user can observe gets no
 * entry and no number — the ledger records releases, not commits.
 */
export const CHANGELOG = [
  {
    version: "1.0.0",
    date: "2026-08-28",
    title: "The whole table rolls at once",
    changes: [
      "Several people can roll at the same time. The board keeps three sets of dice now, so a throw no longer waits for whoever pressed first — only your own rail stays shut until your dice have stopped.",
      "Throws come in from whichever corner the roll picks, so two in the air together land where they can be told apart. Every chair still watches the same tumble and reads the same number.",
      "The Dungeon Master deals every piece onto the board. A player moves their own once it is down and takes it off through its menu, but putting it out is the head of the table’s.",
      "A campaign save carries 4 MB of pictures. Hang more maps than that and it says so before anything is uploaded, rather than failing on the way.",
    ],
    fixes: [
      "The arrow that follows a token being dragged is visible to the whole table on a map with no grid on it. It only ever travelled in cells, and an unruled board has none.",
      "Hit points, tokens and everything else that moves live stop snapping back to where they were and forward again when several changes land at once.",
      "A log line waiting on the database wears the portrait of whoever wrote it — hit points, chests, packs and purses all showed a blank disc until the real line arrived.",
    ],
  },
  {
    version: "0.18.0",
    date: "2026-08-28",
    title: "Roll for initiative, and a light to carry into the dark",
    changes: [
      "Combat, called from a new mark at the top of the Dungeon Master’s rail. It opens an initiative ladder above the activity log, and the log keeps the half it had.",
      "The ladder is one order read down the middle: the party down the left, whatever the table invented down the right, each on the rung its number puts it on. Type a number beside any piece standing on the board.",
      "Start combat, then Next turn walks the order and counts the rounds. Off the bottom is the top again.",
      "Whose turn it is glows amber — on the rung, and around that character’s portrait on the party rail. Every chair sees it, not the Dungeon Master alone.",
      "The frame around the board burns red while a fight is running, and the log says when one begins and ends.",
      "Fog of war. Every map is pitch black to the party until somebody opens it, and only the Dungeon Master can.",
      "Reveal and Hide are brushes, with a width beside them. Paint on the board and the party sees it once both brushes are put down — never mid-stroke.",
      "The Dungeon Master sees through their own fog, so there is something to aim a brush at.",
      "The party’s marker is a gold pin now rather than a lettered disc, and it appears on the world map under the world lore as well as on the board — so a player can check where the party is without taking the fight off the table.",
      "Gnome, Half-Orc and Halfling have their artwork. All nine races have one now.",
      "A campaign can invent five pieces of its own — a picture and a name each, made on the campaign sheet — and the Dungeon Master deals them onto any battle map from the rail. As many copies as the encounter needs; a coloured rim tells them apart.",
      "Right-click a piece on the board for what can be done to it: put it out of sight, strike it down, say what it is suffering, or take it off. A press that goes nowhere no longer lifts one.",
      "A hidden piece is the Dungeon Master’s alone. It is not sent to a player’s browser at all, so there is nothing faint on their board to give the surprise away.",
      "A character’s piece wears their card. Kill them anywhere and the rail and the board say it in the same breath.",
    ],
    fixes: [
      "The trays on the rail beside the board no longer spill their contents over the map while opening and closing.",
      "An armour class set by hand follows the sheet again. Raising Dexterity used to move it only until somebody typed a number over it, and then never again.",
    ],
  },
  {
    version: "0.17.0",
    date: "2026-08-27",
    title: "A face, a shelf of maps, and a grid to stand on",
    changes: [
      "Characters carry a portrait. Drop a picture on the circle at the top of the sheet and it is resized and re-encoded in your browser before it is uploaded; it shows on every card, token and log line. Without one, a cameo on your own colour.",
      "That colour is now your DICE colour, and the creation sheet throws a real d20 in it beside the swatches — the same die the table rolls. It no longer changes itself while you type a name.",
      "The Dungeon Master's dice keep their obsidian. A secret roll is the same die, lettered in violet.",
      "A campaign can keep ten maps besides its world map, added on the campaign sheet and listed under a new Maps tab, where any picture can be swapped without reopening the sheet.",
      "A map switcher at the table, for the Dungeon Master alone: pick a map and every chair cross-fades to it, with no page reload anywhere.",
      "Any map can be ruled with a hex grid — a toggle, a size and a black-to-white contrast slider, all three live as you drag them. Tokens grow to their cell and snap to it.",
      "One hex is five feet. Drag a token and an arrow follows the pointer with the distance in feet; hold the right button and it measures without moving anything, and the whole table watches it.",
      "The Dungeon Master deals tokens out from a row of party faces beside the board and can move anybody's. On an unruled map every player still places and lifts their own.",
      "The board zooms on the scroll wheel now, towards whatever is under the pointer, and the left button belongs to the tokens.",
    ],
  },
  {
    version: "0.16.0",
    date: "2026-08-27",
    title: "The rest of what a character is",
    changes: [
      "Death saves. A card at zero hit points shows three successes and three failures, and the player rolls their own — a blow big enough for massive damage skips them entirely.",
      "An armour class under the level ring on every card. It starts where 5e says — ten plus Dexterity, plus Constitution for a Barbarian or Wisdom for a Monk — and follows the sheet until somebody types over it.",
      "The fifteen conditions, in the session panel, for one character or the whole party. Whatever somebody is under is listed at the foot of their card.",
      "Hit dice: one per level, of your class’s own size. A long rest hands half of them back and says how many.",
      "A second page on the scores panel with initiative, speed, passive perception, size and the hit dice left, and the armour, weapon and tool proficiencies your class grants under them.",
      "Saving throws on the ability cards, for the two your class is proficient in.",
      "Features and feats. The owner writes their own from the sheet and the Dungeon Master writes them onto anybody at their table, and the whole party can read them.",
      "The Dungeon Master can type over any ability score from the scores panel. Everything follows: the modifier, the save, every skill, passive perception, initiative, the spell save DC, the armour class and the hit-point bar.",
      "Only the Dungeon Master can end a character, and only they can bring one back. Nobody rolls somebody else’s death saves.",
      "Notes above the map can be edited and deleted now, not only written.",
      "The character sheet page carries the table’s own panels: the pack, the spellbook, the experience bar and the features grid.",
    ],
    fixes: [
      "Inspiration fills from the bottom up and empties from the top, rather than the other way round.",
      "A new character starts with no inspiration. It is something a Dungeon Master hands you, and a row that began full had already spent the gesture.",
    ],
  },
  {
    version: "0.15.0",
    date: "2026-08-26",
    title: "What a session costs",
    changes: [
      "A cog under the chest beside the map, and it is the Dungeon Master’s: rests and experience for the party, or for any few of it, chosen from the same dropdown the chest uses.",
      "Short and long rest. A long one fills every bar and every spell slot; a short one returns Pact Magic. Hover either to be told which.",
      "Experience, given and taken back. The bar fills, and the level moves on its own when it crosses — up when it fills, and back down if the experience is taken away again.",
      "Levels are no longer nudged by hand. The arrows have gone from the party cards; experience is the only thing that moves a level now.",
      "Max HP is worked out rather than typed. Your hit die, your level and your Constitution decide it, and the box on the character sheet is now a read-out that answers as you pick a class or move the score. Raise Constitution at eighth level and all eight levels are paid for.",
      "Three marks of inspiration beside every party card. Players spend their own and cannot hand one back; the Dungeon Master gives and takes, and sees the whole party’s.",
      "Roll a handful. A box above the dice says how many go at once — up to twenty — and drops back to one after every throw.",
      "Casting a spell no longer throws dice for you. The log carries what it deals; you roll it on the rail, where the table can watch.",
      "The chest and the session share one panel. Press either mark and it changes shape rather than closing and opening again.",
      "Party pills carry the face at the capsule’s left end, which fits a party of six on one line. Spinner arrows are gone from every number box.",
    ],
    fixes: [
      "The table no longer flashes as though the page had reloaded. Anything that quietly re-read itself — somebody joining, a level moving, or just coming back to the tab — faded the whole board out and back, map and log with it.",
      "Dice are visible again after that. The board they land on was being rebuilt underneath the roller, which went on rolling where nobody could see it — only the number arrived, and it stayed that way until the page was reloaded.",
    ],
  },
  {
    version: "0.14.0",
    date: "2026-08-25",
    title: "Something to keep it in",
    changes: [
      "Bags and chests, written down on the campaign page beside your items and spells: what kind it is, what it is called, and what goes in it. Both start empty-handed — a bag belongs to nobody until it is handed over, and a chest stays out of sight until it is found.",
      "A chest beside the map, opposite the dice, and it is the Dungeon Master's. Open it to fill any container at the table, hand a bag to whoever should be carrying it, or reveal a chest — to one player, to a few, or to the whole party.",
      "A chest revealed to you appears in your pack, under your bags. Take what you want out of it, however much of it there is, and it lands in your hands.",
      "Every bag you carry is a section of its own inside the pack, and items move between them: press Move on anything you are holding and choose where it goes. Coin stays with the character, as it always has.",
      "Pass a bag with everything in it. One press hands the whole thing to a teammate, and the table's log says who was shown a chest, who took what out of one, and who was handed a bag.",
    ],
  },
  {
    version: "0.13.0",
    date: "2026-08-25",
    title: "The table answers at once",
    changes: [
      "Everything at the table happens on the press now. Damage and healing, a level awarded, coin spent or handed over, an item used or dropped, a spell cast, a token put down on the map — the number moves as your finger leaves the button, and the writing goes off behind it. There is no pause to sit through any more.",
      "The line in the activity log arrives with the deed rather than a moment after it, so what you just did is already written where the table reads it.",
      "Press again without waiting. Call four damage and then six and both land, one on top of the other, instead of the second press being locked out until the first has been to the server and back. Nothing at the table greys itself out mid-session any more.",
      "A refusal now says so, in a message at the corner of the screen. Every deed here paints before it is written, so by the time the table says no the drawer has usually shut — those answers used to have nowhere to go and were simply lost.",
      "The board keeps its place while it works. Opening a drawer, rolling dice, or somebody else moving a bar no longer redraws the map, the dice or the cards that had nothing to do with it — so the dice never stutter mid-throw and a panel you are reading stays where you left it.",
      "Coming back to a tab you left open is quick again. It used to fetch the whole table over and over, once for every part of it that was listening.",
      "The table’s log is written by the database itself now, in the same breath as the thing it describes. A hit point and the line about it can no longer disagree, and neither can go missing without the other.",
    ],
    fixes: [
      "Damage called out by two people at once no longer loses one of them. Hit points travelled as a total worked out before the round trip, so if the Dungeon Master and a player both moved the same bar in the same moment, whichever arrived second quietly undid the first — and the log recorded the smaller number as though that was what had been called.",
      "Two quick presses of a level arrow no longer show the whole table a level nobody awarded. The ring used to ride back down to the first press’s answer before climbing again.",
      "Taking more coin than somebody has leaves the right amount behind. A take of fifty against a purse holding three used to leave the Dungeon Master’s drawer showing forty-seven gold that did not exist.",
      "A line already in the activity log no longer slides in again every time something else happens at the table.",
      "The map no longer keeps a stale token after a mark is refused, and the marks re-read themselves rather than the whole board.",
    ],
  },
  {
    version: "0.12.0",
    date: "2026-08-25",
    title: "Spells, and what they cost",
    changes: [
      "A fifth mark above the board, beside the scores: the spellbook. Search the rulebook by name and write what you find into a character’s book, where it shelves itself by level — cantrips first, then first through ninth, three names to a row.",
      "Press a spell and it opens in a panel of its own under the book: casting time, range and duration across the top, the dice and the saving throw under them, then the rule as written and what a bigger slot buys. The list stays where it is while you read.",
      "Cast from that panel. A cantrip goes at once; a levelled spell lays its slots out beside the button and you choose which one it comes out of. The book closes, the dice for that slot land on the map, and the table’s log says who cast what, at what level, and what it came to.",
      "Spell slots at the foot of the book, worked out from the class and the level rather than typed in. Every progression the rulebook has: full casters, paladins and rangers, the arcane archer, and a warlock’s pact magic, which is all one level at a time.",
      "Slots are spent by casting and come back from the head of the table. A player reads their own and cannot move them, the same line hit points and coin are already drawn on.",
      "The save DC and the attack bonus stand at the top of the book, worked out from the class’s own ability, the proficiency bonus and the score on the sheet.",
      "The campaign’s Items tab is now Create. Choose what you are making first, then write it down with every field the rulebook gives it — a spell’s school, components and duration, an item’s price, weight, damage and properties. The table finds both from its own searches.",
      "The pack reads like the spellbook now: a page of names, three across, and the one you press opens underneath. Damage, armour class, range, properties, price and weight all in their own place, and the rule behind Versatile or Thrown written out where a spell writes its own.",
      "How many is a box you type in. The plus and minus buttons are gone from the pack, and Grant and Take in the purse are words rather than slabs.",
      "Searching for a character to invite answers as you type, the way the pack and the spellbook already do. The Search button is gone.",
    ],
    fixes: [
      "The level buttons beside Cast no longer nudge the row down when they appear. They were two pixels taller than the button they sat next to, which moved every control in the row — including the one just pressed.",
      "Closing a mark forgets what was open under it. A spell or an item left standing there used to be waiting the next time the book was opened.",
      "An item’s figures no longer read as its description. The price, the weight and the dice used to be run together into the sentence under its name; they have their own place now, and the sentence is the rulebook’s own words.",
    ],
  },
  {
    version: "0.11.0",
    date: "2026-08-24",
    title: "A pen for the sheet",
    changes: [
      "A pen at the end of the tabs on your character sheet. Press it and the sheet you filled in to make them opens back over the page with everything already in it — the name, the race, the class, the alignment, the scores — and folds shut again behind the save.",
      "The campaign page has the same pen, on the same sheet: the title, the world you wrote, and the map. Swap the map and the old picture is deleted once the new one is safely in.",
      "Hit points belong to the character now. Say how many they have when you make them, in the box beside the race, and every bar at the table is drawn against that number instead of a flat hundred.",
      "The eighteen skills are on the sheet. Tick what your character is trained in and the proficiency bonus is worked out for you from their level; type a number beside one only when a piece of gear or a class feature is worth something on top.",
      "The character page prints all eighteen with what each is worth, trained ones lit in gold, and the proficiency bonus over the top of them. The scores above read what you bought and what it is worth — Base 12 · Mod +1.",
      "A fourth mark above the board, beside the pack: the scores and the skills, the same two sections the character page prints. A player opens their own. The Dungeon Master picks a name along the top and reads any of the party's, the way they already pick a pack.",
      "The Dungeon Master's roll comes out from under the board it was thrown onto, instead of appearing beside the party cards where nobody had rolled it.",
    ],
    fixes: [
      "A card's health bar is drawn against that character's own maximum. It used to be a flat hundred for everybody, so a character with twenty hit points looked nearly dead at full health.",
      "The Dungeon Master's coin capsules dim and turn the pointer away while a grant or a take is with the server, the way a player's already did. They used to sit bright and pressable through the whole wait.",
      "The Max HP box lines its number up with the tag above it rather than centring it in a column of its own.",
    ],
  },
  {
    version: "0.10.4",
    date: "2026-08-24",
    title: "Coin on the table",
    changes: [
      "Every character has a purse now, and it sits above the pack: copper, silver, electrum, gold and platinum, each in a capsule the colour of its own metal, so you find the gold before you have read a word.",
      "A player sees exactly what they are carrying. Press a coin and it opens underneath — say how much, then use it or hand it to somebody across the table. It is the same question the pack already asks, with the same answer on the right of it.",
      "The Dungeon Master types into the capsules instead. The number resting in each one is what that purse holds; type over it and that is what will move, then Grant or Take. Pick a name to aim at one character, or leave it on the whole party and pay everybody at once.",
      "Paying the party is one movement, not six. Either every purse at the table is credited or none is, so a hoard divided at the table cannot half-arrive.",
      "Taking more than somebody has takes what they have. Ask for 9999 gold from a purse holding three and it takes the three — and the log says three, because that is what happened.",
      "Coins move on every screen as they are moved. Hand fifty gold across the table and it leaves your purse and arrives in theirs in front of everybody, with nobody reloading anything.",
      "The log reads money by its colour. Coin arriving is the pale blue of a hand-over, coin crossing the table is a deeper blue, and coin that is gone — spent, or taken back by the Dungeon Master — is darker still.",
      "The amount box on a character card asks for HP rather than showing a 10, which read as a number already typed there.",
    ],
    fixes: [
      "Spending, giving, granting and taking now wait for the table to be told before they can be pressed again — the same way awarding a level already does. A quick second press could otherwise land before the first was written down, and one of them would go missing from a log that only keeps ten.",
    ],
  },
  {
    version: "0.10.3",
    date: "2026-08-23",
    title: "What the table remembers",
    changes: [
      "A log down the left of the board, opposite the dice: the last ten things this table has seen, newest at the top. Who rolled what, who was hurt or healed, what came out of whose pack — written as each of them happens, on every screen at once.",
      "Using something no longer writes a line into your character's notes. It goes to the table's log instead, where the rest of the session already is and where everybody can read it.",
      "The Dungeon Master can level the party from the board. Rest on a character's ring and an arrow rises out from under it, above and below; press one and the number rolls over — the old one out through the floor, the new one down through the ceiling. The log says who went to what, gold for a level gained and brown for one taken back.",
      "Health has moved off the foot of the board and onto the party cards, under the name it belongs to. You see your own; a Dungeon Master sees the whole party's, one under each.",
      "The bar is the button. Click it and the card opens underneath: an amount, then Damage or Heal, and it closes again behind the press. The pencil that used to sit beside it is gone.",
      "A roll announces itself as it leaves the hand. The pill beside the roller's card comes out with the die already on it rather than waiting for the number, so the table knows whose throw is in the air — and a kept roll says one is happening without saying what it is.",
      "The globe, the scroll and the pack share one panel now. It stands in the middle of the board whichever you press, the arrow slides across to the mark you chose, and the contents grow into one another instead of one box closing while another opens.",
      "Leaving the table is the arrival run backwards: the marks step back behind the board, and the board shrinks away after them. Pressing the gold star to come in grows it past the page while the table opens behind it.",
    ],
  },
  {
    version: "0.10.2",
    date: "2026-08-22",
    title: "What the party carries",
    changes: [
      "The pack above the map has something in it at last. Open it as a player and there is everything your character is carrying, a card each with its count: say how many and use them, drop them, or hand them to somebody across the table.",
      "The Dungeon Master's pack is the whole party's. Pick a name from the row along the top to see what they are carrying and take any of it back, or leave it on the whole party and give the same thing to every one of them at once.",
      "Search the rulebook without leaving the board. Type two letters and the equipment and magic items come back as cards — the name, what kind of thing it is, and what it actually does — and whichever you pick goes into the pack you aimed at.",
      "An Items tab on the campaign page, for everything the rulebook has never heard of. Write down a rusted key or a bag of rats once and it is there in the table's search from then on, ahead of the rulebook's own.",
      "Handing something over is one movement rather than two. It leaves your pack and arrives in theirs together, so nothing can be lost in between — and a Dungeon Master can move loot around their own party the same way.",
      "Loot arrives as it is handed out. A Dungeon Master giving the party torches puts one in every pack on every screen, and nobody reloads anything.",
      "Using something writes itself into your notes — “Used Potion of Healing” — so the session keeps its own ledger of what was spent.",
      "Use, drop and give all ask first, with the number in the question, and the answer that does the thing sits on the right of it every time.",
      "The same items are read back under Inventory on the character sheet, where nothing can be spent. What a party is carrying is settled at the table, in front of whoever is running it.",
    ],
  },
  {
    version: "0.10.1",
    date: "2026-08-22",
    title: "One roll, every screen",
    changes: [
      "Dice down the rail beside the board, d4 through d100. Press one and it is thrown onto the map: it tumbles across the world, comes to rest on a face, and the number slides out from under your card.",
      "Everybody at the table watches the same throw. Not a picture of it and not a number arriving afterwards — the same dice, the same tumble, the same face, on every screen at once.",
      "The Dungeon Master can draw a veil over the rail. The boards turn violet for the whole table while a kept roll is in the air, so everyone knows something is being rolled and nobody but the roller learns what came up.",
      "Ask for stillness in your system settings and the dice are not thrown at all — the number simply arrives.",
    ],
    fixes: [
      "Hit points somebody else changed never changed on your screen. A Dungeon Master could take half a party's health off and every player would keep looking at full bars until they reloaded the page.",
      "Tokens put on the map took a couple of seconds to reach anybody else. They arrive as they are put down now, which is what this app has been claiming since the table opened.",
      "Leaving the table left your card lit in everybody else's party rail for several seconds after you had gone. You stand up as you go now.",
      "Somebody who accepted an invitation while you were already at the table never appeared in your party until you reloaded. They arrive as they sit down.",
      "The party rail went dark and relit itself whenever the connection so much as blinked, which read as the whole party standing up and sitting back down.",
    ],
  },
  {
    version: "0.10.0",
    date: "2026-08-21",
    title: "A seat at the table",
    changes: [
      "The gold star opens the table now: the campaign's board, with the world in the middle and the party down the side. Pressing it on a character's sheet seats you as that character; pressing it on a campaign's page seats you at the head of the table.",
      "The map is the board. Click to zoom in on it, drag or use the arrow keys to travel across it, and click again to come back out.",
      "Right-click the map to put your token down, and right-click the token to lift it again. A player marks with their character's own face, the Dungeon Master with the party's gold token — and may clear anybody's.",
      "Marks arrive as they are made. Everybody at the table is looking at the same board, without anyone reloading it.",
      "The party sits down the right, a card each with its level in a ring, and a card lights gold for as long as its player has the table open.",
      "Hit points are kept now rather than drawn at full on every visit, so the bar on a character's sheet shows what they actually have left.",
      "Health runs along the bottom of the board: a player watches their own, the Dungeon Master watches the whole party's and holds the pen over all of it. Type an amount and give it or take it — seven damage, four healed — rather than working out anybody's new total.",
      "A scroll above the map for writing notes while you play. A player's are read back under Notes on their character sheet; a Dungeon Master keeps their own book, on a new Notes tab on the campaign page. Beside it a globe, for reading the world's lore without leaving the board, and a pack, which stays empty until loot exists.",
      "The table arrives rather than appears: the campaign's name converges out of wide-spaced letters, the map grows into the middle, its frame blooms around it, and the party falls in down the rail. The grimoire in the corner stands down for as long as you are playing.",
    ],
  },
  {
    version: "0.9.1",
    date: "2026-08-21",
    title: "A knock at the seal",
    changes: [
      "The envelope in the bar answers when something lands in it: it grows, rocks itself still, and settles back down.",
      "The ruby pip waits for that to finish before dropping onto the seal, rather than lighting up beside it. It plays again each time something new arrives.",
    ],
    fixes: [
      "The unread pip sat in the air above the envelope instead of on its corner.",
      "The envelope was the one control in the bar that did not light up under the pointer.",
    ],
  },
  {
    version: "0.9.0",
    date: "2026-08-20",
    title: "Sealed missives",
    changes: [
      "A wax-sealed envelope in the bar across the top, and everything waiting for you behind it. A ruby pip glows on the seal while something is unanswered.",
      "Dungeon Masters now invite a character rather than adding one. The player finds the invitation in their own keeping and answers it — accepting puts their character in the party, declining says no, and the Dungeon Master's party list fills in the moment they do.",
      "Nobody's character can be enlisted without their say-so any more. Being findable by your handle is an invitation to be asked, not a way to be signed up.",
      "A note arrives whenever the app has been updated, with a way straight into this grimoire from it.",
      "Invitations and party changes arrive on their own. No reloading the page to find out whether anybody answered.",
      "The missives panel unfolds downwards out of the seal and folds back up into it, and sits centred under the envelope that opens it.",
    ],
  },
  {
    version: "0.8.1",
    date: "2026-08-20",
    title: "Doors on every room",
    changes: [
      "Every page opens and closes now rather than cutting. Sheets, the creation panel, settings and the sign-in card unfold out of a line of light; the dashboard's cards glide in from the sides and slide back out the way they came.",
      "The bar across the top drops into place when a page is opened fresh, and leaves over the top when you sign out. Moving between the signed-in pages leaves it where it is.",
      "The settings page is one panel rather than three stacked cards, and the sign-in page types its own name out.",
    ],
    fixes: [
      "Panels flashed at full size for an instant before folding open.",
      "Opening the full-size map stuttered the first time, while the picture was still arriving. It is now fetched the moment you reach for the preview.",
    ],
  },
  {
    version: "0.8.0",
    date: "2026-08-19",
    title: "Hit points, and doors that open",
    changes: [
      "A health bar on the character sheet, reading gold while a character is holding up, amber once they are bloodied, and red with a heartbeat under it near the end.",
      "Character sheets, campaign pages and the creation panel now open: a line of light that unfolds into the card, and then the contents arrive.",
      "Switching between tabs on a sheet fades the panels instead of cutting, and the card grows or shrinks to fit the one you picked rather than jumping.",
      "The sign-in card grows and shrinks between signing in and creating an account, and the new fields slide in rather than appearing.",
      "The full-size map grows out of its preview and folds back into it, and can be worked from the keyboard throughout.",
    ],
    fixes: [
      "The full-size map showed black bars down both sides that the preview does not, and snapped back to the preview's framing at the end of closing.",
      "Opening the changelog darkened the room in one step while the panel was still sliding in. The two now travel together.",
      "The dashboard flickered on the way to and from the creation panel, and the empty slots came back with their glass broken.",
      "Tab panels no longer add their hidden height to the page, which was putting a scrollbar on tabs that had nothing to scroll.",
    ],
  },
  {
    version: "0.7.1",
    date: "2026-08-18",
    title: "What a party may see",
    fixes: [
      "The full-size map could not be worked from the keyboard at all, while telling anyone using one to drag it. Tab reaches it now, Enter zooms, and the arrow keys move around while zoomed.",
      "Adding a character to a campaign showed the Dungeon Master more of that character than a card does — their backstory and personality among it. A party now sees only what is printed on the card.",
      "A map that was still too large after compression left the form unable to submit and no way to clear it short of reloading the page.",
      "A file that could not be read as an image was accepted as a map and then drawn as a broken picture. It now says so when you choose it.",
      "Removing somebody from a party could report an error at the same moment it worked.",
      "The dashboard was sending every character's whole sheet to the browser, backstory and all, to draw cards that show five things.",
      "The drop zone for a map kept its error outline only until the pointer touched it.",
    ],
  },
  {
    version: "0.7.0",
    date: "2026-08-18",
    title: "Dungeon Masters and ability scores",
    changes: [
      "Ability scores on the character sheet: fifteen points to spend across the six, from 7 to 15, with the last two points of any score costing double. Your race adds its own on top, and the sheet shows the total and its modifier.",
      "Campaigns, up to three of them. Give one a title, the lore the party already knows, and a world map — the map is scaled and re-encoded in your browser before it is sent, so a 20MB export leaves as about one.",
      "A campaign page with the lore, the map and the party. The map opens full size; click it to zoom in, drag to move around, click again to come back out.",
      "Add characters to a party by searching for a name, an id, or both — fri, 1000 and fri#10 all find the same elf. Six to a party.",
      "A character sheet names the campaigns it plays in, beside the character's name.",
      "The dashboard shows its own slot count for characters and for campaigns, in each section rather than once at the top.",
    ],
    fixes: [
      "Character sheets stopped loading entirely — every tab, for everyone — once campaigns existed. Two security rules each asked the other a question, and the database refused to answer either.",
      "Switching between tabs on a sheet threw away whatever the tab you left was holding. A map you had opened at full size downloaded itself again on the way back.",
      "Choosing a map could make the file larger than the one you picked, and store it at a lower resolution as well.",
    ],
  },
  {
    version: "0.6.1",
    date: "2026-08-16",
    title: "Steadier ground",
    fixes: [
      "When the sign-in service could not be reached, the app said your session had expired — so you signed in, got sent back, and signed in again. It now tells you the service is unreachable, and says so instead of asking you to prove who you are.",
      "The loading bar across the top no longer slides for anyone who has asked their system to reduce motion. It still appears while a page is on its way.",
    ],
  },
  {
    version: "0.6.0",
    date: "2026-08-15",
    title: "The grimoire mark",
    changes: [
      "The grimoire itself is now the app's mark — beside the wordmark in the header, and on the browser tab.",
      "A rebuilt sign-in page: the book and the tale it opens sit on glass beside the card, and fold underneath it on a narrow screen.",
      "Signing in and out carries the book across the screen instead of cutting to the next page. It flies to the dashboard's corner, turning as it goes, and flies back when you leave.",
      "This panel, opened from the book in that corner.",
    ],
  },
  {
    version: "0.5.0",
    date: "2026-08-15",
    title: "Grimoire Tales",
    changes: [
      "The whole app redesigned: ivory and gold on near-black, Cinzel for headings, and liquid glass surfaces throughout.",
      "A two-step class picker — five archetypes, thirteen paths — on the character sheet, shown on the card afterwards.",
      "Character cards carry the artwork for their race, a name you can click to copy the full handle, and a Notes tab on the sheet.",
    ],
    fixes: [
      "Backstory and Personality rejected text at or under 2000 characters. Each paragraph break secretly counted twice, so the real ceiling was 2000 minus the number of them.",
      "Character cards forced themselves wider than their column and overlapped each other at every screen size.",
      "A name made of a single emoji passed the form and then came back as a raw database error.",
      "The password reveal button could not be reached with the keyboard.",
      "Session cookies are no longer readable by scripts on the page.",
      "Two accounts creating characters at the same instant could slip past the three-per-account limit.",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-08-13",
    title: "The animated background",
    changes: [
      "A living background of drifting gold paths behind every page.",
      "The app is committed to its dark appearance rather than following the system theme, which was leaving light-mode visitors with near-black text on black.",
      "Proper not-found and error screens instead of the framework's own.",
    ],
    fixes: [
      "Asking for reduced motion and then resizing the window permanently blanked the background's glow and motes.",
      "The still frame drawn for reduced motion ran its whole simulation in one go and froze the page while it did.",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-08-13",
    title: "Race artwork",
    changes: [
      "Character cards show the artwork for their race behind the details.",
    ],
    fixes: [
      "Replacing a race's artwork left everyone looking at the old picture until their browser cache expired.",
      "The play button's light sweep followed the star's spin instead of crossing it.",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-08-11",
    title: "Settings and character sheets",
    changes: [
      "A settings page for your display name, email address and password.",
      "Each character has a sheet of their own, with tabs and a play button.",
      "The project split into a frontend and a backend that knows nothing about the framework.",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-08-10",
    title: "Accounts and characters",
    changes: [
      "Sign up, sign in, and stay signed in.",
      "Create up to three characters, each with a race, an alignment, a colour and a history.",
      "A name and a four-digit tag together make a handle a Dungeon Master can invite.",
    ],
  },
];
